### ISSUE TITLE
Github file error while pushing!!!

### ISSUE THREAD

**Issue by Thanarat-Vachiruckul** [cadsondemak/K2D#1]
เรียนทีมงาน google font

ผมพบปัญหาการอัพไฟล์ฟอนต์ k2d july8.glyphs บน github desktop หลังจากกด commit to master แล้วจะ push ไฟล์ ปรากฏว่าโปรแกรมแจ้งเตือน error เหมือนไฟล์มีปัญหาบางอย่าง จึงได้ลองกด ok ไปเพื่อทดลอง push ขึ้นไปก่อนว่าปัญหาคืออะไร ซึ่งไฟล์ก็ push ได้ปกติครับ แต่เมื่อกลับมาเช็คไฟล์ผลปรากฏว่าไฟล์ฟอนต์ที่อยู่ใน source ในเครื่องพัง glyph ในไฟล์เหลือแค่ 6 glyph ที่เหลือลบหายไปหมด คาดว่าไฟล์ที่ push ขึ้นไปก็น่าจะเสียไปด้วย (ตอนที่ลองกด push นั้นคิดว่าจะ error ยังไงก็ไม่น่าจะมีผลกับตัวไฟล์ฟอนต์)

ผมจึงได้ทดลองเอาไฟล์ฟอนต์ k2d july8.glyphs ตัวเดิมที่ backup ไว้ก่อนจะพังมาลอง push ดูอีกครั้ง เพื่อหาสาเหตุ คาดว่าเมื่อ push ใหม่ก็จะ error เหมือนเดิม แต่ผลปรากฏว่าไฟล์ push ได้ปกติ จึงอนุมานได้ว่าน่าจะ error ที่ตัวโปรแกรม github desktop เอง

ตี้เองก็แจ้งมาว่าเจอปัญหาการเตือน error นี้เช่นกันแต่ไฟล์ไม่มีปัญหาอะไร

วิธีแก้ไขตอนนี้แนะนำทีมที่ออกแบบ backup ไฟล์ไว้ด้วยนะครับ อาจจะทำทุกครั้งก่อนจะ push ไฟล์หรือบ่อยกว่านั้นได้ก็เป็นการดีครับ

**Comment by davelab6** [comment]
I think that you could try a few ways to resolve this. 

One is to make sure everything is up to date and checked in, and then make a branch, and push that branch, and then use the branch comparison feature of Github to compare the master branch on Github with your new branch. 

One is to save a new glyphs file (that has all the glyphs) and add and commit that file, then make a second commit to delete to the old file, and then push those 2 commits. 

Also, I found that the Github GUI is convenient for making simple every-day commits and pushing them, but when I find a problem, it is easier to use Terminal to run the git commands step by step and see more informative error output. If you are not familiar with Terminal, find a colleague who is who can help you :) 

Finally, I can recommend a different approach to using Git; at the moment you are making all your changes, saving as you go, and then once a week you make a huge git commit and try to push it. Many things can happen during this time and problems can sit and grow without being seen. Instead, make a commit each time you use the "save" function of Glyphs, and add a small comment (less than 70 characters, can be in Thai :) as the commit message. Then there is a nice historical record of the project, and any errors will be quickly seen as they happen.

**Comment by Thanarat-Vachiruckul** [comment]
Thank you so much for your suggestion.

**Comment by davelab6** [comment]
At https://github.com/cadsondemak/K2D/commits/master I see a new commit, so I guess this is resolved :)

<img width="1240" alt="screen shot 2018-02-25 at 19 45 22" src="https://user-images.githubusercontent.com/261579/36648670-723ccb04-1a64-11e8-8c21-4e4cc41cfe23.png">

However, this commit message is not very informative; we can see the date of the commit in metadata. What actually changed? Since it was many days since the last commit, I expect a lot of things changed :) 

I want to repeat what I said before: 

> Finally, I can recommend a different approach to using Git; at the moment you are making all your changes, saving as you go, and then once a week you make a huge git commit and try to push it. Many things can happen during this time and problems can sit and grow without being seen. Instead, make a commit each time you use the "save" function of Glyphs, and add a small comment (less than 70 characters, can be in Thai :) as the commit message. Then there is a nice historical record of the project, and any errors will be quickly seen as they happen.
