### ISSUE TITLE
Design Note

### ISSUE THREAD

**Issue by AnuthinWongsunkakon** [cadsondemak/K2D#2]
@Thanarat-Vachiruckul Please start putting up the design note here as we have discussed.

**Comment by Thanarat-Vachiruckul** [comment]
![screen shot 2018-04-03 at 3 42 59 pm](https://user-images.githubusercontent.com/35482151/38238999-c9bfb194-3755-11e8-883d-7ff43b936d37.png)


a re-design for latin alphabets ( Master 200).

![screen shot 2018-04-03 at 3 44 29 pm](https://user-images.githubusercontent.com/35482151/38239074-f5c4b38e-3755-11e8-839e-16b3f2f7a85c.png)

I try to keep original design so that ink-trap identity is maintained (A tiny ink-trap must be part of the design but not a main idea of the font).

**Comment by Thanarat-Vachiruckul** [comment]
Below : Original Thai alphabets
![screen shot 2018-04-03 at 2 44 36 pm](https://user-images.githubusercontent.com/35482151/38236489-7df00d9c-374e-11e8-9e88-6554bbf9a26e.png)

A revised version
![screen shot 2018-04-03 at 2 43 47 pm](https://user-images.githubusercontent.com/35482151/38236514-97a1c262-374e-11e8-9f14-f82a66e752e7.png)

![screen shot 2018-04-03 at 2 35 42 pm](https://user-images.githubusercontent.com/35482151/38236545-b0ec9846-374e-11e8-89e5-6ddf1173650d.png)

**Comment by AnuthinWongsunkakon** [comment]
I think you are in a good shape. As we discussed in person at Chonburi office last week. Although the ink trap design is a bit overkilled in my opinion but I totally understand that it is a feature from the original design. We shall keep them there. The question is how would it be in the bolder weight.  Are you up to that point yet? 

The Latin is a bit strange because the whole set is trying to pronounce capsulate design but Q and O are going for perfect circle design. I think we shall stick with the original design. What do you think? @SmichSmanloh  and @davelab6 ?

**Comment by Thanarat-Vachiruckul** [comment]
Thank you for your suggestion. As we discussed, the large ink-trap for bolder weight would be a good idea. Here is some solution for bold >

![screen shot 2018-05-01 at 2 36 08 pm](https://user-images.githubusercontent.com/35482151/39465509-fa6f91c0-4d4d-11e8-871f-fa693dce432e.png)

![screen shot 2018-05-01 at 2 42 29 pm](https://user-images.githubusercontent.com/35482151/39465518-0c47ee88-4d4e-11e8-9db4-32ab77598a01.png)

**Comment by Thanarat-Vachiruckul** [comment]
Latin Master 400

![screen shot 2018-05-15 at 12 49 39 pm](https://user-images.githubusercontent.com/35482151/40039202-97635de4-583f-11e8-98cd-2c035ab24528.png)

Thai Master 400

![screen shot 2018-05-15 at 12 54 11 pm](https://user-images.githubusercontent.com/35482151/40039210-a14a6d34-583f-11e8-829b-2291ca9b27e4.png)
